### ISSUE TITLE
Do not observe symbols.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define-object#12]
I think if someone tries:

```js
var s = new Symbol();

o = new DefineObject();

ObservationRecorder.start();
o[s]
var records = ObservationRecorder.stop();
```

`records` will include something for the symbol.  This creates unnecessary bindings. We should __never__ listen to a symbol property.

**Comment by matthewp** [comment]
What bug does this cause?

**Comment by phillipskevin** [comment]
It just causes extra observations. Any reason you think we shouldn't make this change @matthewp?

**Comment by matthewp** [comment]
Not really. There might be some future use-case where symbols are used for, for example, private event names, and you might want to be able to bind for that. But I guess we can change that in the future.
