### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-object#2]
This is a meta issue for all of the documentation needed. Much of this comes from the [design doc](https://github.com/canjs/can-define-object/wiki/Design-doc).

* [x] `static define = {}`
* [x] getters/setters on the prototype
* [ ] DefineObject
* [ ] DefineArray
* [x] `static items = Todo`
* [x] `type.maybe()`
* [x] `type.convert()`
* [x] `type.check()`
* [x] `type.maybeConvert()`
* [x] `type.Any`
* [x] `static propertyDefaults = {}`
* [x] `new ExtendedDefineClass({propNotDefined: "value"})`
* [x] `static seal = false`

## PropDefinitions

* [x] `age: 36` - default
* [x] `age: Number` primitive constructor
* [x] `age: NumberType` constructor
* [x] `age: type.convert(Number)` using can-type
* [x] `age: function() { }` Used as the default value
* [x] `age: {}` propDefinition

### PropDefinitions object

* [x] `type`
* [x] ` default:  Primitive | Function | Object`
* [x] `get default() { }`
* [x] `get() { }`
* [x] `set( [newVal] [,lastSet] ){}`
* [x] `async( [resolve] ){}`
* [x] `value( {resolve, listenTo, stopListening, lastSet}){}`
* [x] `required: Boolean=false`
* [x] `enumerable: Boolean`
* [x] `serialize(value): Any`

**Comment by justinbmeyer** [comment]
## Sidebar

![image](https://user-images.githubusercontent.com/78602/58897344-b2e7fe00-86bd-11e9-92fa-31a2bddb06fd.png)

- [ ] Should `static` come first?
- [ ] We might want better names for `Property` and `PropDefinition`.  Maybe `Property` and `DefinitionObject`?

## Pages

- [ ] https://canjs.com/doc/can-define-object.html -> https://docs.google.com/document/d/1KwOt75xc4Sr69Fcam40Ork9ou2VsifdRk2AHE1CktwY/edit?usp=sharing

**Comment by justinbmeyer** [comment]
## define/default 

> __Any__ value can be provided as the default value used for this property, like:

We might want to warn in the signature that this should typically be used for `Primitive` values.

**Comment by justinbmeyer** [comment]
## define/enumerable

> enumerable Defines whether

Start with an active verb.

>  By default, all properties except for ones with defined `getters`

`value` and `async` too right?

> Prevent a property from being serialized like:

What else does `enumerable` control?  

- Object.assign(), spread
- for...in loop and Object.keys()

Might want to link to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Enumerable_attribute.

**Comment by justinbmeyer** [comment]
## define/get-default

> array using the next call signature below, 

What call signature?

**Comment by justinbmeyer** [comment]
## define/required

> `const secondMap = new MyMap({});`

Is throwing `can-define: the definition for MyMap{}.propertyName uses a constructor for 'type'. Did you mean 'Type'?` ... this seems wrong.

**Comment by justinbmeyer** [comment]
## define/serialize

> serialize Defines custom serialization behavior for a property.

This should start with an active verb.

**Comment by justinbmeyer** [comment]
## define/set 

We should let people know that `type` runs before `set`.

**Comment by justinbmeyer** [comment]
## define/type 


![image](https://user-images.githubusercontent.com/78602/58900015-eaf23f80-86c3-11e9-80c8-9cd3c4b8fd2a.png)


`instances` seems to be hanging.

**Comment by justinbmeyer** [comment]
## object.static.define

https://canjs.com/doc/can-define-object/object.static.define.html

![image](https://user-images.githubusercontent.com/78602/58900271-7a97ee00-86c4-11e9-9250-934bfe5b6102.png)


It would be nice to reference `Property` here somehow.  

```
static define = Object<String,Property>
```

This can definitely be done in the `parameters`.

**Comment by justinbmeyer** [comment]
# object.static.seal

> console.error( error.name + ": " + error.message ); //-> "TypeError: Cannot add property age, object is not extensible"

Might want to break this in 2 lines so there's no horizontal scroll in the code example.

**Comment by justinbmeyer** [comment]
## object.types.property

Other:

- it would be nice to have a single schema and example like the design wiki has
